spring:
  application:
    name: bs56-spring-cloud-admin-feign

server:
  port: 8765

eureka:
  instance:
    prefer-ip-address: true  #以ip地址注册到服务中心  方便追溯服务
  client:
    serviceUrl:
      defaultZone: http://192.168.2.87:8761/eureka/


feign:
  hystrix:
    enabled: true   #feign自带熔断器，但是默认关闭，所有需要打开